version: 2.1.1
last_compiled: 2025-10-31 11:58:42

# ================================================
# Compiled with the following settings:
#
# To change these settings, run C:\Users\qsoren\agent-os\scripts\project-update.ps1 to re-compile your project with the new settings.
# ================================================
profile: default
claude_code_commands: true
use_claude_code_subagents: true
agent_os_commands: false
standards_as_claude_code_skills: false